image:
  repository: nagarjuncsrecloud/image-api
  tag: latest

service:
  type: LoadBalancer
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
